"""Core TUI runtime primitives inspired by pi-tui architecture."""

from probid_tui.core.ansi_utils import (
    strip_ansi,
    truncate_to_width,
    truncate_to_width_with_ellipsis,
    truncateToWidth,
    visible_width,
    visibleWidth,
    wrap_text_with_ansi,
    wrapTextWithAnsi,
)
from probid_tui.core.component import Component, Focusable, is_focusable, isFocusable
from probid_tui.core.editor import Editor
from probid_tui.core.keys import (
    LEGACY_KEYS,
    Key,
    KeyEventType,
    KeyId,
    decode_kitty_printable,
    decodeKittyPrintable,
    is_key_release,
    is_key_repeat,
    is_kitty_protocol_active,
    isKeyRelease,
    isKeyRepeat,
    isKittyProtocolActive,
    matches_key,
    matchesKey,
    parse_key,
    parseKey,
    set_kitty_protocol_active,
    setKittyProtocolActive,
    split_input_sequences,
)
from probid_tui.core.terminal import ProcessTerminal, Terminal
from probid_tui.core.tui_runtime import (
    CURSOR_MARKER,
    Container,
    OverlayAnchor,
    OverlayHandle,
    OverlayMargin,
    OverlayOptions,
    SizeValue,
    TUI,
)

__all__ = [
    "strip_ansi",
    "truncate_to_width",
    "truncate_to_width_with_ellipsis",
    "truncateToWidth",
    "visible_width",
    "visibleWidth",
    "wrap_text_with_ansi",
    "wrapTextWithAnsi",
    "Component",
    "Focusable",
    "is_focusable",
    "isFocusable",
    "Editor",
    "LEGACY_KEYS",
    "Key",
    "KeyId",
    "KeyEventType",
    "is_key_repeat",
    "is_kitty_protocol_active",
    "set_kitty_protocol_active",
    "decode_kitty_printable",
    "isKeyRelease",
    "isKeyRepeat",
    "isKittyProtocolActive",
    "setKittyProtocolActive",
    "decodeKittyPrintable",
    "is_key_release",
    "matches_key",
    "matchesKey",
    "parse_key",
    "parseKey",
    "split_input_sequences",
    "ProcessTerminal",
    "Terminal",
    "CURSOR_MARKER",
    "OverlayAnchor",
    "OverlayHandle",
    "OverlayMargin",
    "OverlayOptions",
    "SizeValue",
    "TUI",
    "Container",
]
